/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  instructor: InstructorReference;
  category: CategoryReference;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  price: number;
  popular?: boolean;
  studentCount?: number;
  outcomes: Array<
    {
      _key: string;
    } & Outcome
  >;
  modules: Array<
    {
      _key: string;
    } & Module
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  posterImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  duration: string;
  freePreview?: boolean;
  studentCount?: number;
  keyPoints: Array<string>;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  expertise: Array<string>;
  bio: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type Resource = {
  _type: "resource";
  type: "pdf" | "video" | "link" | "code" | "article" | "download" | "other";
  title: string;
  description?: string;
  url: string;
};

export type Outcome = {
  _type: "outcome";
  icon: string;
  title: string;
  description: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | InstructorReference
  | CategoryReference
  | SanityImageAssetReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Lesson
  | Instructor
  | Category
  | LessonReference
  | Module
  | Resource
  | Outcome
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
}>;

// Source: ../web/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    description  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
} | null;

// Source: ../web/sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(title asc) {      _id,  title,  "slug": slug.current,  summary,  "coverImage": coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },  level,  price,  popular,  studentCount,  "category": category->{   _id,  title,  "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  "photo": photo {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },  expertise },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  };
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    };
    expertise: Array<string>;
  };
  moduleCount: number;
  lessonCount: number;
}>;

// Source: ../web/sanity/queries/courses.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{ "slug": slug.current }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  summary,  "coverImage": coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },  level,  price,  popular,  studentCount,  "category": category->{   _id,  title,  "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  "photo": photo {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },  expertise },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons),    "outcomes": outcomes[]{   _key,  icon,  title,  description },    "modules": modules[]{      _key,      title,      summary,      "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  duration,  freePreview,  studentCount,  "posterImage": posterImage {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt } }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  };
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    };
    expertise: Array<string>;
  };
  moduleCount: number;
  lessonCount: number;
  outcomes: Array<{
    _key: string;
    icon: string;
    title: string;
    description: string;
  }>;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      duration: string;
      freePreview: boolean | null;
      studentCount: number | null;
      posterImage: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        alt: string;
      } | null;
    }>;
  }>;
} | null;

// Source: ../web/sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    "photo": photo {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },    expertise,    bio,    "courses": *[_type == "course" && references(^._id) && defined(slug.current)] | order(title asc) {      _id,      title,      "slug": slug.current,      summary,      "coverImage": coverImage {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },      level    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  };
  expertise: Array<string>;
  bio: string;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
    };
    level: "advanced" | "beginner" | "intermediate";
  }>;
} | null;

// Source: ../web/sanity/queries/instructors.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)]{ "slug": slug.current }
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../web/sanity/queries/lessons.ts
// Variable: LESSON_BY_COURSE_AND_SLUG_QUERY
// Query: *[    _type == "lesson" &&    slug.current == $lessonSlug &&    _id in *[_type == "course" && slug.current == $courseSlug][0].modules[].lessons[]._ref  ][0]{    _id,    title,    "slug": slug.current,    videoUrl,    "posterImage": posterImage {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },    duration,    freePreview,    studentCount,    notes,    keyPoints,    proTip,    "resources": resources[]{   _key,  type,  title,  description,  url },    "course": *[_type == "course" && slug.current == $courseSlug][0]{      _id,      title,      "slug": slug.current,      "instructor": instructor->{   _id,  name,  "slug": slug.current,  "photo": photo {   asset->{ _id, url, metadata { lqip, dimensions } },  hotspot,  alt },  expertise },      "category": category->{   _id,  title,  "slug": slug.current },      "modules": modules[]{        _key,        title,        "lessonIds": lessons[]._ref      }    }  }
export type LESSON_BY_COURSE_AND_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  posterImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
  } | null;
  duration: string;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string>;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "code" | "download" | "link" | "other" | "pdf" | "video";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        alt: string;
      };
      expertise: Array<string>;
    };
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    modules: Array<{
      _key: string;
      title: string;
      lessonIds: Array<string>;
    }>;
  } | null;
} | null;

// Source: ../web/sanity/queries/lessons.ts
// Variable: COURSE_LESSON_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)]{    "courseSlug": slug.current,    "lessonSlugs": modules[].lessons[]->slug.current  }
export type COURSE_LESSON_SLUGS_QUERY_RESULT = Array<{
  courseSlug: string;
  lessonSlugs: Array<string>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    description\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  "coverImage": coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n  level,\n  price,\n  popular,\n  studentCount,\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  "photo": photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n  expertise\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons)\n\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]{ "slug": slug.current }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  "coverImage": coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n  level,\n  price,\n  popular,\n  studentCount,\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  "photo": photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n  expertise\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons)\n,\n    "outcomes": outcomes[]{ \n  _key,\n  icon,\n  title,\n  description\n },\n    "modules": modules[]{\n      _key,\n      title,\n      summary,\n      "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  duration,\n  freePreview,\n  studentCount,\n  "posterImage": posterImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n }\n }\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    "photo": photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n    expertise,\n    bio,\n    "courses": *[_type == "course" && references(^._id) && defined(slug.current)] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      "coverImage": coverImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n      level\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)]{ "slug": slug.current }\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "lesson" &&\n    slug.current == $lessonSlug &&\n    _id in *[_type == "course" && slug.current == $courseSlug][0].modules[].lessons[]._ref\n  ][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    "posterImage": posterImage { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n    duration,\n    freePreview,\n    studentCount,\n    notes,\n    keyPoints,\n    proTip,\n    "resources": resources[]{ \n  _key,\n  type,\n  title,\n  description,\n  url\n },\n    "course": *[_type == "course" && slug.current == $courseSlug][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  "photo": photo { \n  asset->{ _id, url, metadata { lqip, dimensions } },\n  hotspot,\n  alt\n },\n  expertise\n },\n      "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n      "modules": modules[]{\n        _key,\n        title,\n        "lessonIds": lessons[]._ref\n      }\n    }\n  }\n': LESSON_BY_COURSE_AND_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]{\n    "courseSlug": slug.current,\n    "lessonSlugs": modules[].lessons[]->slug.current\n  }\n': COURSE_LESSON_SLUGS_QUERY_RESULT;
  }
}
